_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
                - 43
                - 49
                - 55
                - 63
            "2":
                - 1
                - 41
                - 43
                - 49
                - 55
                - 63
            "3":
                - 23
                - 35
                - 55
            "4": 3.8.20
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
